### ISSUE TITLE
Some videos are skipped + ValueError

### ISSUE THREAD

**Issue by anthony-wss** [anthony-wss/video-face-detection#1]
1. Some videos are skipped during frames extraction.
2. `ValueError: A 2-dimensional array must be passed.`

```shell
➜  video-face-detection git:(main) ✗ bash run.sh ../europa ../europa_frames
progress: 1%
progress: 2%
progress: 3%
progress: 4%
progress: 5%
[h264 @ 0x557f6cba3e00] reference picture missing during reorder
[h264 @ 0x557f6cba3e00] Missing reference picture, default is 66032
[h264 @ 0x557f6cba3e00] mmco: unref short failure
progress: 6%
progress: 7%
progress: 8%
progress: 9%
progress: 10%
[h264 @ 0x563a81f61f80] co located POCs unavailable
    Last message repeated 2 times
[h264 @ 0x563a81f61f80] mmco: unref short failure
[h264 @ 0x563a81f61f80] co located POCs unavailable
progress: 11%
progress: 12%
progress: 13%
[h264 @ 0x56131ff139c0] mmco: unref short failure
[h264 @ 0x56131ff139c0] reference picture missing during reorder
[h264 @ 0x56131ff139c0] Missing reference picture, default is 66034
progress: 14%
progress: 15%
progress: 16%
progress: 17%
progress: 18%
  7%|█████████                                                                                                                          | 13/188 [00:43<09:39,  3.31s/it]
Traceback (most recent call last):
  File "/work/u3937558/meta-project/video-face-detection/main.py", line 90, in <module>
    distance_matrix = pdist(all_embs, metric='euclidean')
  File "/home/u3937558/.local/lib/python3.10/site-packages/scipy/spatial/distance.py", line 2200, in pdist
    raise ValueError('A 2-dimensional array must be passed.')
ValueError: A 2-dimensional array must be passed.
```

**Comment by anthony-wss** [comment]
The ValueError issue is fixed in https://github.com/anthony-wss/video-face-detection/commit/f4536bc7d9e2daff2945cc02b6978cda7f8fdaae
